print("Hello")
number = input("enter a number from 1 to 12")
noun =input("enter a noun(plural)")
name=input("enter a name")
scream=input("enter a sentence:")
verb=input("enter a verb")
print()
print("it was %s o'clock when i heard a knock at the door."%(time))
print('I opened the door and there was a box full of %s with a note saying "from M. %s."' % (noun,name.title()))
